project:
  type: website

website:
  title: "Constance Beaufils"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - lumen
    css: styles.css
    toc: true

editor: visual

